//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleApp.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting activity with id &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionDeleteActivity {
            get {
                return ResourceManager.GetString("ExceptionDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while consultant with id &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionDeleteConsultant {
            get {
                return ResourceManager.GetString("ExceptionDeleteConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting provider with id &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionDeleteProvider {
            get {
                return ResourceManager.GetString("ExceptionDeleteProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while retriving Activity for Id &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionGetActivity {
            get {
                return ResourceManager.GetString("ExceptionGetActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while retriving Consultant for Id &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionGetConsultant {
            get {
                return ResourceManager.GetString("ExceptionGetConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while retriving all activities.
        /// </summary>
        internal static string ExceptionGetForAllActivitys {
            get {
                return ResourceManager.GetString("ExceptionGetForAllActivitys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while retriving all consultants.
        /// </summary>
        internal static string ExceptionGetForAllConsultants {
            get {
                return ResourceManager.GetString("ExceptionGetForAllConsultants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while retriving all Providers.
        /// </summary>
        internal static string ExceptionGetForAllProviders {
            get {
                return ResourceManager.GetString("ExceptionGetForAllProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while retriving Provider for id &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionGetProvider {
            get {
                return ResourceManager.GetString("ExceptionGetProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while inserting activity &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionInsertActivity {
            get {
                return ResourceManager.GetString("ExceptionInsertActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while inserting consultant &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionInsertConsultant {
            get {
                return ResourceManager.GetString("ExceptionInsertConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while inserting provider &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionInsertProvider {
            get {
                return ResourceManager.GetString("ExceptionInsertProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating activity &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionUpdateActivity {
            get {
                return ResourceManager.GetString("ExceptionUpdateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating consultant &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionUpdateConsultant {
            get {
                return ResourceManager.GetString("ExceptionUpdateConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating provider &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionUpdateProvider {
            get {
                return ResourceManager.GetString("ExceptionUpdateProvider", resourceCulture);
            }
        }
    }
}
